In [1]:
import numpy as np

# Create a one-dimensional array (vector) with the first 10 positive integers
vector = np.arange(1, 11)

# Display the values of the vector
print("Array with the first 10 positive integers:")
print(vector)


Array with the first 10 positive integers:
[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
import numpy as np

# Create a two-dimensional array (matrix) of size 3x3 filled with zeros
matrix = np.zeros((3, 3))

# Display the values of the matrix
print("Matrix filled with zeros:")
print(matrix)


Matrix filled with zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
import numpy as np

# Create a 5x5 array filled with random integers ranging from 1 to 10
array = np.random.randint(1, 11, size=(5, 5))

# Display the values of the array
print("Array filled with random integers ranging from 1 to 10:")
print(array)


Array filled with random integers ranging from 1 to 10:
[[10  6  8  7  4]
 [ 1  3  9  9  8]
 [ 7 10  5  8  3]
 [ 6  4  6  7  6]
 [ 9  8  4  7  3]]


In [4]:
import numpy as np

# Create a 4x4 array filled with random floating-point numbers ranging from 0 to 1
array = np.random.rand(4, 4)

# Display the values of the array
print("Array filled with random floating-point numbers ranging from 0 to 1:")
print(array)


Array filled with random floating-point numbers ranging from 0 to 1:
[[0.90250284 0.48718957 0.85363652 0.21367507]
 [0.183426   0.41443948 0.28136561 0.57549801]
 [0.83642906 0.49106879 0.39637309 0.39260018]
 [0.51211005 0.63389038 0.20758773 0.01906882]]


In [5]:
import numpy as np

# Create two one-dimensional arrays of size 5 filled with random integers ranging from 1 to 10
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

# Display the values of the arrays
print("Array 1 filled with random integers ranging from 1 to 10:")
print(array1)
print("\nArray 2 filled with random integers ranging from 1 to 10:")
print(array2)

# Perform addition, subtraction, and multiplication operations on the arrays
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

# Display the results of the operations
print("\nAddition of the two arrays:")
print(addition)
print("\nSubtraction of the two arrays:")
print(subtraction)
print("\nMultiplication of the two arrays:")
print(multiplication)


Array 1 filled with random integers ranging from 1 to 10:
[5 9 9 5 9]

Array 2 filled with random integers ranging from 1 to 10:
[2 9 8 5 7]

Addition of the two arrays:
[ 7 18 17 10 16]

Subtraction of the two arrays:
[3 0 1 0 2]

Multiplication of the two arrays:
[10 81 72 25 63]


In [6]:
import numpy as np

# Create two vectors of size 7 filled with random numbers
vector1 = np.random.rand(7)
vector2 = np.random.rand(7)

# Display the values of the vectors
print("Vector 1 filled with random numbers:")
print(vector1)
print("\nVector 2 filled with random numbers:")
print(vector2)

# Calculate the dot product (scalar product) of the vectors
dot_product = np.dot(vector1, vector2)

# Display the dot product of the vectors
print("\nDot product of the two vectors:")
print(dot_product)


Vector 1 filled with random numbers:
[0.83058126 0.79469029 0.83186931 0.22000734 0.5548954  0.01901672
 0.90180089]

Vector 2 filled with random numbers:
[0.35741352 0.47149295 0.76067772 0.42940488 0.61310738 0.8294748
 0.42306637]

Dot product of the two vectors:
2.1363145081621697


In [7]:
import numpy as np

# Create two matrices of sizes 2x2 and 2x3 filled with random integers ranging from 1 to 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

# Display the values of the matrices
print("Matrix 1 filled with random integers ranging from 1 to 10:")
print(matrix1)
print("\nMatrix 2 filled with random integers ranging from 1 to 10:")
print(matrix2)

# Multiply the matrices
product = np.dot(matrix1, matrix2)

# Display the product of the matrices
print("\nProduct of the two matrices:")
print(product)


Matrix 1 filled with random integers ranging from 1 to 10:
[[8 3]
 [9 3]]

Matrix 2 filled with random integers ranging from 1 to 10:
[[ 4  9  7]
 [ 7 10  7]]

Product of the two matrices:
[[ 53 102  77]
 [ 57 111  84]]


In [8]:
import numpy as np

# Create a 3x3 matrix filled with random integers ranging from 1 to 10
matrix = np.random.randint(1, 11, size=(3, 3))

# Display the values of the matrix
print("Matrix filled with random integers ranging from 1 to 10:")
print(matrix)

# Calculate the inverse of the matrix
try:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nInverse of the matrix:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("\nMatrix is singular and its inverse cannot be computed.")


Matrix filled with random integers ranging from 1 to 10:
[[ 2 10  7]
 [ 5  6 10]
 [ 2  1  8]]

Inverse of the matrix:
[[-0.21965318  0.42196532 -0.33526012]
 [ 0.11560694 -0.01156069 -0.0867052 ]
 [ 0.04046243 -0.10404624  0.21965318]]


In [9]:
import numpy as np

# Create a 4x4 matrix filled with random floating-point numbers ranging from 0 to 1
matrix = np.random.rand(4, 4)

# Display the values of the matrix
print("Matrix filled with random floating-point numbers ranging from 0 to 1:")
print(matrix)

# Transpose the matrix
transposed_matrix = np.transpose(matrix)

# Display the transposed matrix
print("\nTransposed matrix:")
print(transposed_matrix)


Matrix filled with random floating-point numbers ranging from 0 to 1:
[[0.24054644 0.26231083 0.35989759 0.40099116]
 [0.01387667 0.53490645 0.18558687 0.0932072 ]
 [0.56537936 0.53042838 0.50830643 0.89020515]
 [0.13506619 0.88510354 0.00622224 0.22562064]]

Transposed matrix:
[[0.24054644 0.01387667 0.56537936 0.13506619]
 [0.26231083 0.53490645 0.53042838 0.88510354]
 [0.35989759 0.18558687 0.50830643 0.00622224]
 [0.40099116 0.0932072  0.89020515 0.22562064]]


In [10]:
import numpy as np

# Create a 3x4 matrix filled with random integers ranging from 1 to 10
matrix = np.random.randint(1, 11, size=(3, 4))

# Create a vector of size 4 filled with random integers ranging from 1 to 10
vector = np.random.randint(1, 11, size=4)

# Display the values of the matrix and vector
print("Matrix:")
print(matrix)
print("\nVector:")
print(vector)

# Multiply the matrix by the vector
result = np.dot(matrix, vector)

# Display the result
print("\nResult of multiplying the matrix by the vector:")
print(result)


Matrix:
[[ 3  6 10  5]
 [ 7  9  8  9]
 [ 3  9  8  1]]

Vector:
[6 6 1 3]

Result of multiplying the matrix by the vector:
[ 79 131  83]


In [11]:
import numpy as np

# Create a 2x3 matrix filled with random floating-point numbers ranging from 0 to 1
matrix = np.random.rand(2, 3)

# Create a vector of size 3 filled with random floating-point numbers ranging from 0 to 1
vector = np.random.rand(3)

# Display the values of the matrix and vector
print("Matrix:")
print(matrix)
print("\nVector:")
print(vector)

# Multiply the matrix by the vector
result = np.dot(matrix, vector)

# Display the result
print("\nResult of multiplying the matrix by the vector:")
print(result)


Matrix:
[[0.31588698 0.67060104 0.66117743]
 [0.11295169 0.04256315 0.49135695]]

Vector:
[0.92675016 0.17693391 0.94100974]

Result of multiplying the matrix by the vector:
[1.03357477 0.57458054]


In [12]:
import numpy as np

# Create two 2x2 matrices filled with random integers ranging from 1 to 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Display the values of the matrices
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)

# Perform element-wise multiplication of the matrices (Hadamard product)
element_wise_product = np.multiply(matrix1, matrix2)

# Display the result of element-wise multiplication
print("\nElement-wise multiplication of the two matrices:")
print(element_wise_product)


Matrix 1:
[[ 1  7]
 [10  8]]

Matrix 2:
[[1 1]
 [7 2]]

Element-wise multiplication of the two matrices:
[[ 1  7]
 [70 16]]


In [13]:
import numpy as np

# Create two 2x2 matrices filled with random integers ranging from 1 to 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Display the values of the matrices
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)

# Perform matrix multiplication
matrix_product = np.dot(matrix1, matrix2)

# Display the result of matrix multiplication
print("\nMatrix product of the two matrices:")
print(matrix_product)


Matrix 1:
[[2 8]
 [3 5]]

Matrix 2:
[[ 2  2]
 [ 6 10]]

Matrix product of the two matrices:
[[52 84]
 [36 56]]


In [14]:
import numpy as np

# Create a 5x5 matrix filled with random integers ranging from 1 to 100
matrix = np.random.randint(1, 101, size=(5, 5))

# Display the values of the matrix
print("Matrix:")
print(matrix)

# Calculate the sum of the elements of the matrix
matrix_sum = np.sum(matrix)

# Display the sum of the elements of the matrix
print("\nSum of the elements of the matrix:", matrix_sum)


Matrix:
[[26 41 96 14  9]
 [46 19 31 76  5]
 [67 55 20  1 89]
 [67 74  1 83 86]
 [71 11 77 76 81]]

Sum of the elements of the matrix: 1222


In [15]:
import numpy as np

# Create two 4x4 matrices filled with random integers ranging from 1 to 10
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

# Display the values of the matrices
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)

# Find the difference between the matrices
difference = matrix1 - matrix2

# Display the difference between the matrices
print("\nDifference between the two matrices:")
print(difference)


Matrix 1:
[[2 7 9 6]
 [3 3 5 8]
 [3 9 7 4]
 [2 3 2 3]]

Matrix 2:
[[10  6  3  5]
 [10  7  7  1]
 [ 9  7  6  2]
 [ 6  4  8  6]]

Difference between the two matrices:
[[-8  1  6  1]
 [-7 -4 -2  7]
 [-6  2  1  2]
 [-4 -1 -6 -3]]


In [16]:
import numpy as np

# Create a 3x3 matrix filled with random floating-point numbers ranging from 0 to 1
matrix = np.random.rand(3, 3)

# Display the values of the matrix
print("Matrix:")
print(matrix)

# Calculate the column vector containing the sum of elements of each row
column_vector = np.sum(matrix, axis=1)

# Display the column vector
print("\nColumn vector containing the sum of elements of each row:")
print(column_vector)


Matrix:
[[0.25015466 0.67468482 0.09551885]
 [0.41381734 0.06550633 0.62924244]
 [0.10825528 0.08793367 0.76523292]]

Column vector containing the sum of elements of each row:
[1.02035833 1.10856611 0.96142188]


In [17]:
import numpy as np

# Utworzenie macierzy o rozmiarze 3x4 z dowolnymi liczbami całkowitymi
macierz = np.random.randint(1, 10, size=(3, 4))

# Utworzenie macierzy zawierającej kwadraty liczb z macierzy pierwotnej
macierz_kwadratow = np.square(macierz)

# Wyświetlenie wartości obu macierzy
print("Macierz pierwotna:")
print(macierz)

print("\nMacierz z kwadratami liczb:")
print(macierz_kwadratow)


Macierz pierwotna:
[[6 9 8 9]
 [7 2 2 4]
 [9 1 7 2]]

Macierz z kwadratami liczb:
[[36 81 64 81]
 [49  4  4 16]
 [81  1 49  4]]


In [18]:
import numpy as np

# Utworzenie wektora o rozmiarze 4 z losowymi liczbami całkowitymi z zakresu od 1 do 50
wektor = np.random.randint(1, 51, size=4)

# Znalezienie pierwiastków kwadratowych z elementów wektora
pierwiastki_kwadratowe = np.sqrt(wektor)

# Wyświetlenie wartości wektora oraz jego pierwiastków kwadratowych
print("Wektor:")
print(wektor)

print("\nPierwiastki kwadratowe z elementów wektora:")
print(pierwiastki_kwadratowe)


Wektor:
[22 15 21  9]

Pierwiastki kwadratowe z elementów wektora:
[4.69041576 3.87298335 4.58257569 3.        ]
